# Generated by Django 4.2.7 on 2023-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_requestqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestqr',
            name='closed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestqr',
            name='entered_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
