# Generated by Django 4.2.7 on 2023-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_request', models.CharField(max_length=50)),
                ('owner_request', models.CharField(max_length=100)),
                ('child_owner', models.CharField(max_length=100)),
                ('child_class', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_at', models.CharField(max_length=100)),
                ('closed_at', models.CharField(max_length=100)),
            ],
        ),
    ]
