# Generated by Django 4.2.7 on 2024-03-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_requestqr_closed_at_alter_requestqr_entered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='students_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.students_class'),
        ),
    ]
